version: '3'
services: 
   web:
       container_name: appJPB
       restart: always
       build: .
       ports: 
           - "3030:3000"
       links: 
           - mongo        
   mongo: 
       container_name: mongodb
       image : mongo 
       ports: 
           - "27018:27017"     
