export {default as MatriculaRepository} from './matricula.repository'
export {default as UsuarioRepository} from './Usuario.repository'
export {default as DepartamentoRepository} from './Departamento.repository'
export {default as ProvinciaRepository} from './Provincia.repository'
export {default as DistritoRepository} from './Distrito.repository'